# .github/workflows/test.yml

name: Run Server Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set working directory
        run: cd Server

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test-ci
